// The directory name of the current module.
console.log(__dirname);         // D:\GitRepo\demo-nodejs\basic-example\Global

// The file name of the current module.
console.log(__filename);        // D:\GitRepo\demo-nodejs\basic-example\Global\global-example.js


// --------------------------------------------------------

console.log(global);
// {
// 	DTRACE_NET_SERVER_CONNECTION: [Function],
// 	DTRACE_NET_STREAM_END: [Function],
// 	DTRACE_HTTP_SERVER_REQUEST: [Function],
// 	DTRACE_HTTP_SERVER_RESPONSE: [Function],
// 	DTRACE_HTTP_CLIENT_REQUEST: [Function],
// 	DTRACE_HTTP_CLIENT_RESPONSE: [Function],
// 	COUNTER_NET_SERVER_CONNECTION: [Function],
// 	COUNTER_NET_SERVER_CONNECTION_CLOSE: [Function],
// 	COUNTER_HTTP_SERVER_REQUEST: [Function],
// 	COUNTER_HTTP_SERVER_RESPONSE: [Function],
// 	COUNTER_HTTP_CLIENT_REQUEST: [Function],
// 	COUNTER_HTTP_CLIENT_RESPONSE: [Function],
// 	global: [Circular],
// 	process: process{
// 		title: 'C: \\ProgramFiles\\JetBrains\\WebStorm2017.2.1\\bin\\runnerw.exe',
// 		version: 'v6.11.2',
// 		moduleLoadList: ['Bindingcontextify',
// 		'Bindingnatives',
// 		'NativeModuleevents',
// 		'NativeModuleutil',
// 		'Bindinguv',
// 		'NativeModulebuffer',
// 		'Bindingbuffer',
// 		'Bindingutil',
// 		'NativeModuleinternal/util',
// 		'NativeModuletimers',
// 		'Bindingtimer_wrap',
// 		'NativeModuleinternal/linkedlist',
// 		'NativeModuleassert',
// 		'NativeModuleinternal/process',
// 		'Bindingconfig',
// 		'NativeModuleinternal/process/warning',
// 		'NativeModuleinternal/process/next_tick',
// 		'NativeModuleinternal/process/promises',
// 		'NativeModuleinternal/process/stdio',
// 		'Bindingconstants',
// 		'NativeModulepath',
// 		'NativeModulemodule',
// 		'NativeModuleinternal/module',
// 		'NativeModulevm',
// 		'NativeModulefs',
// 		'Bindingfs',
// 		'NativeModulestream',
// 		'NativeModuleinternal/streams/legacy',
// 		'NativeModule_stream_readable',
// 		'NativeModuleinternal/streams/BufferList',
// 		'NativeModule_stream_writable',
// 		'NativeModule_stream_duplex',
// 		'NativeModule_stream_transform',
// 		'NativeModule_stream_passthrough',
// 		'Bindingfs_event_wrap',
// 		'NativeModuleconsole',
// 		'Bindingtty_wrap',
// 		'NativeModulenet',
// 		'NativeModuleinternal/net',
// 		'Bindingcares_wrap',
// 		'Bindingtcp_wrap',
// 		'Bindingpipe_wrap',
// 		'Bindingstream_wrap'],
// 		versions: {
// 			http_parser: '2.7.0',
// 			node: '6.11.2',
// 			v8: '5.1.281.103',
// 			uv: '1.11.0',
// 			zlib: '1.2.11',
// 			ares: '1.10.1-DEV',
// 			icu: '58.2',
// 			modules: '48',
// 			openssl: '1.0.2l'
// 		},
// 		arch: 'x64',
// 		platform: 'win32',
// 		release: {
// 			name: 'node',
// 			lts: 'Boron',
// 			sourceUrl: 'https: //nodejs.org/download/release/v6.11.2/node-v6.11.2.tar.gz',
// 			headersUrl: 'https: //nodejs.org/download/release/v6.11.2/node-v6.11.2-headers.tar.gz',
// 			libUrl: 'https: //nodejs.org/download/release/v6.11.2/win-x64/node.lib'
// 		},
// 		argv: ['C: \\ProgramFiles\\nodejs\\node.exe',
// 		'D: \\GitRepo\\demo-nodejs\\basic-example\\Global\\global-example.js'],
// 		execArgv: [],
// 		env: {
// 			ALLUSERSPROFILE: 'C: \\ProgramData',
// 			ANT_HOME: 'D: \\Tools\\apache-ant-1.9.7',
// 			APPDATA: 'C: \\Users\\bribin.zheng\\AppData\\Roaming',
// 			CommonProgramFiles: 'C: \\ProgramFiles\\CommonFiles',
// 			'CommonProgramFiles(x86)': 'C: \\ProgramFiles(x86)\\CommonFiles',
// 			CommonProgramW6432: 'C: \\ProgramFiles\\CommonFiles',
// 			COMPUTERNAME: 'XMN113',
// 			ComSpec: 'C: \\Windows\\system32\\cmd.exe',
// 			DEBUG_COLORS: 'true',
// 			DEBUG_FD: '1',
// 			ELECTRON_NO_ATTACH_CONSOLE: 'true',
// 			FORCE_COLOR: 'true',
// 			FPS_BROWSER_APP_PROFILE_STRING: 'InternetExplorer',
// 			FPS_BROWSER_USER_PROFILE_STRING: 'Default',
// 			GRADLE_HOME: 'D: \\Tools\\gradle-2.12',
// 			HerokuPath: 'C: \\ProgramFiles(x86)\\Heroku',
// 			HOMEDRIVE: 'C: ',
// 			HOMEPATH: '\\Users\\bribin.zheng',
// 			JAVA_HOME: 'C: \\ProgramFiles\\Java\\jdk1.8.0_131',
// 			LOCALAPPDATA: 'C: \\Users\\bribin.zheng\\AppData\\Local',
// 			LOGONSERVER: '\\\\CH-XMN-DC03',
// 			M2_HOME: 'D: \\Tools\\apache-maven-3.3.9',
// 			MOCHA_COLORS: '1',
// 			MOZ_PLUGIN_PATH: 'C: \\ProgramFiles(x86)\\FoxitSoftware\\FoxitReader\\plugins\\',
// 			NUMBER_OF_PROCESSORS: '8',
// 			OneDrive: 'C: \\Users\\bribin.zheng\\OneDrive',
// 			OS: 'Windows_NT',
// 			Path: 'C: \\ProgramData\\Oracle\\Java\\javapath;C: \\ProgramFiles\\Java\\jdk1.8.0_131\\bin;C: \\Python27\\;C: \\Python27\\Scripts;C: \\Windows\\system32;C: \\Windows;C: \\Windows\\System32\\Wbem;C: \\Windows\\System32\\WindowsPowerShell\\v1.0\\;C: \\ProgramFiles\\Git\\cmd;C: \\HashiCorp\\Vagrant\\bin;C: \\ProgramFiles\\TortoiseHg\\;C: \\ProgramFiles(x86)\\Heroku\\bin;D: \\_source\\commands;C: \\oracle\\product\\11.2.0\\client_1\\bin;D: \\Tools\\apache-maven-3.3.9\\bin;D: \\Tools\\gradle-2.12\\bin;D: \\Tools\\apache-ant-1.9.7\\bin;C: \\ProgramFiles(x86)\\Skype\\Phone\\;C: \\Windows\\system32\\config\\systemprofile\\.dnx\\bin;C: \\ProgramFiles\\MicrosoftDNX\\Dnvm\\;C: \\ProgramFiles(x86)\\WindowsKits\\8.1\\WindowsPerformanceToolkit\\;C: \\ProgramFiles\\MicrosoftSQLServer\\130\\Tools\\Binn\\;C: \\ProgramFiles\\TortoiseSVN\\bin;C: \\ProgramFiles\\nodejs\\;C: \\ProgramFiles\\TortoiseGit\\bin;C: \\Ruby23-x64\\bin;C: \\Users\\bribin.zheng\\AppData\\Local\\Programs\\Fiddler;C: \\Users\\bribin.zheng\\AppData\\Roaming\\npm',
// 			PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW',
// 			PROCESSOR_ARCHITECTURE: 'AMD64',
// 			PROCESSOR_IDENTIFIER: 'Intel64Family6Model94Stepping3,
// 			GenuineIntel',
// 			PROCESSOR_LEVEL: '6',
// 			PROCESSOR_REVISION: '5e03',
// 			ProgramData: 'C: \\ProgramData',
// 			ProgramFiles: 'C: \\ProgramFiles',
// 			'ProgramFiles(x86)': 'C: \\ProgramFiles(x86)',
// 			ProgramW6432: 'C: \\ProgramFiles',
// 			PSModulePath: 'C: \\ProgramFiles\\WindowsPowerShell\\Modules;C: \\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C: \\ProgramFiles\\Intel\\',
// 			PUBLIC: 'C: \\Users\\Public',
// 			SESSIONNAME: 'Console',
// 			SystemDrive: 'C: ',
// 			SystemRoot: 'C: \\Windows',
// 			TEMP: 'C: \\Users\\BRIBIN~1.ZHE\\AppData\\Local\\Temp',
// 			TMP: 'C: \\Users\\BRIBIN~1.ZHE\\AppData\\Local\\Temp',
// 			USERDNSDOMAIN: 'RCOFFICE.RINGCENTRAL.COM',
// 			USERDOMAIN: 'RCOFFICE',
// 			USERDOMAIN_ROAMINGPROFILE: 'RCOFFICE',
// 			USERNAME: 'bribin.zheng',
// 			USERPROFILE: 'C: \\Users\\bribin.zheng',
// 			VBOX_MSI_INSTALL_PATH: 'C: \\ProgramFiles\\Oracle\\VirtualBox\\',
// 			VS140COMNTOOLS: 'C: \\ProgramFiles(x86)\\MicrosoftVisualStudio14.0\\Common7\\Tools\\',
// 			windir: 'C: \\Windows'
// 		},
// 		pid: 13668,
// 		features: {
// 			debug: false,
// 			uv: true,
// 			ipv6: true,
// 			tls_npn: true,
// 			tls_alpn: true,
// 			tls_sni: true,
// 			tls_ocsp: true,
// 			tls: true
// 		},
// 		_needImmediateCallback: false,
// 		execPath: 'C: \\ProgramFiles\\nodejs\\node.exe',
// 		debugPort: 5858,
// 		_startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
// 		_stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
// 		_getActiveRequests: [Function: _getActiveRequests],
// 		_getActiveHandles: [Function: _getActiveHandles],
// 		reallyExit: [Function: reallyExit],
// 		abort: [Function: abort],
// 		chdir: [Function: chdir],
// 		cwd: [Function: cwd],
// 		umask: [Function: umask],
// 		_kill: [Function: _kill],
// 		_debugProcess: [Function: _debugProcess],
// 		_debugPause: [Function: _debugPause],
// 		_debugEnd: [Function: _debugEnd],
// 		hrtime: [Function: hrtime],
// 		cpuUsage: [Function: cpuUsage],
// 		dlopen: [Function: dlopen],
// 		uptime: [Function: uptime],
// 		memoryUsage: [Function: memoryUsage],
// 		binding: [Function: binding],
// 		_linkedBinding: [Function: _linkedBinding],
// 		_setupDomainUse: [Function: _setupDomainUse],
// 		_events: {
// 			warning: [Function],
// 			newListener: [Function],
// 			removeListener: [Function]
// 		},
// 		_rawDebug: [Function],
// 		_eventsCount: 3,
// 		domain: null,
// 		_maxListeners: undefined,
// 		_fatalException: [Function],
// 		_exiting: false,
// 		assert: [Function],
// 		config: {
// 			target_defaults: [Object],
// 			variables: [Object]
// 		},
// 		emitWarning: [Function],
// 		nextTick: [Function: nextTick],
// 		_tickCallback: [Function: _tickCallback],
// 		_tickDomainCallback: [Function: _tickDomainCallback],
// 		stdout: [Getter],
// 		stderr: [Getter],
// 		stdin: [Getter],
// 		openStdin: [Function],
// 		exit: [Function],
// 		kill: [Function],
// 		argv0: 'C: \\ProgramFiles\\nodejs\\node.exe',
// 		mainModule: Module{
// 			id: '.',
// 			exports: {
//
// 			},
// 			parent: null,
// 			filename: 'D: \\GitRepo\\demo-nodejs\\basic-example\\Global\\global-example.js',
// 			loaded: false,
// 			children: [],
// 			paths: [Object]
// 		}
// 	},
// 	Buffer: {
// 		[Function: Buffer]poolSize: 8192,
// 		from: [Function],
// 		alloc: [Function],
// 		allocUnsafe: [Function],
// 		allocUnsafeSlow: [Function],
// 		isBuffer: [Function: isBuffer],
// 		compare: [Function: compare],
// 		isEncoding: [Function],
// 		concat: [Function],
// 		byteLength: [Function: byteLength]
// 	},
// 	clearImmediate: [Function],
// 	clearInterval: [Function],
// 	clearTimeout: [Function],
// 	setImmediate: [Function],
// 	setInterval: [Function],
// 	setTimeout: [Function],
// 	console: [Getter]
// }


console.log(module);
// Module {
//     id: '.',
//     exports: {},
//     parent: null,
//     filename: 'D:\\GitRepo\\demo-nodejs\\basic-example\\Global\\global-example.js',
//     loaded: false,
//     children: [],
//     paths:
//     [ 'D:\\GitRepo\\demo-nodejs\\basic-example\\Global\\node_modules',
//         'D:\\GitRepo\\demo-nodejs\\basic-example\\node_modules',
//         'D:\\GitRepo\\demo-nodejs\\node_modules',
//         'D:\\GitRepo\\node_modules',
//         'D:\\node_modules' ] }


// --------------------------------------------------------

console.log(process);
console.log(process.pid);


// --------------------------------------------------------

